name: Database Explorer CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: 'explorer'
          POSTGRES_PASSWORD: 'explorer'
          POSTGRES_DB: 'explorer'
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: "Asia/Tokyo"
        timezoneMacos: "Asia/Tokyo"
        timezoneWindows: "Tokyo Standard Time"

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install SSH server
      run: sudo apt-get install -y openssh-server

    - name: Setup SSH server
      run: |
        sudo service ssh start
        echo 'PermitRootLogin yes' | sudo tee -a /etc/ssh/sshd_config
        sudo service ssh restart

    - name: Setup user for SSH
      run: |
        echo "Create a new user"
        sudo useradd -m explorer
        echo "Set password for the new user"
        echo explorer:explorer | sudo chpasswd

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --stacktrace --info --debug
